name: tony
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  otp_text_field: ^1.1.3
  google_nav_bar: ^5.0.6
  syncfusion_flutter_barcodes: ^23.1.42
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  provider: ^6.0.5
  screen_brightness: ^0.2.2+1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: UberMove
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf
          weight: 500
        - asset: assets/fonts/UberMoveBold.otf
          weight: 700
